# Generated by Django 4.1.7 on 2024-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=100)),
                ('officnamber', models.CharField(max_length=100)),
                ('namberkart', models.CharField(max_length=100)),
                ('shebanamber', models.CharField(max_length=100)),
                ('melicodebank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='castmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peyment', models.CharField(max_length=100)),
                ('melicodevarizande', models.CharField(max_length=100)),
                ('selectjob', models.CharField(max_length=100)),
                ('bankonvan', models.CharField(max_length=100)),
                ('persone', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('mounth', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
