# Generated by Django 4.1.7 on 2024-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=100)),
                ('officnamber', models.CharField(max_length=100)),
                ('namberkart', models.CharField(max_length=100)),
                ('shebanamber', models.CharField(max_length=100)),
                ('melicodebank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='castmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idf', models.CharField(default='0', max_length=20)),
                ('melicodvarizande', models.CharField(default='0', max_length=10)),
                ('dateshamsi', models.CharField(default='0', max_length=100)),
                ('datemiladi', models.CharField(default='0', max_length=100)),
                ('filenumber', models.CharField(default='0', max_length=100)),
                ('cashmethodname', models.CharField(default='0', max_length=100)),
                ('cashmethodid', models.CharField(default='0', max_length=100)),
                ('melicodeoperatore', models.CharField(default='0', max_length=100)),
                ('mablagh', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='casttestmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(default='0', max_length=20)),
                ('s', models.CharField(default='0', max_length=100)),
                ('c', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ctmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idf', models.CharField(default='0', max_length=20)),
                ('melicod', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='listmodeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
