# Generated by Django 4.1.7 on 2024-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='timeditor',
            field=models.CharField(blank=True, default='noedit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='cashmethodid',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='cashmethodname',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='datemiladi',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='dateshamsi',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='filenumber',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='idf',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='mablagh',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='melicodeoperatore',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='melicodvarizande',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
