# Generated by Django 4.1.7 on 2024-09-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='cashmethodid',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='cashmethodname',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='datemiladi',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='dateshamsi',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='idf',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='mablagh',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='melicodeoperatore',
        ),
    ]
