# Generated by Django 4.1.7 on 2024-09-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='timeditor',
        ),
    ]
