# Generated by Django 4.1.7 on 2024-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=100)),
                ('officnamber', models.CharField(max_length=100)),
                ('namberkart', models.CharField(max_length=100)),
                ('shebanamber', models.CharField(max_length=100)),
                ('melicodebank', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='bank_model',
        ),
    ]
