# Generated by Django 4.1.7 on 2024-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0002_remove_castmodel_timeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='timeditor',
            field=models.CharField(default='noedit', max_length=10),
        ),
    ]
