# Generated by Django 4.1.7 on 2024-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0002_remove_castmodel_cashmethodid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='datemiladi',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='dateshamsi',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='dateshamsieditor',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='idf',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
