# Generated by Django 4.1.7 on 2024-09-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0002_castmodel_timeditor_alter_castmodel_cashmethodid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castmodel',
            old_name='timeditor',
            new_name='ditor',
        ),
    ]
