# Generated by Django 4.1.7 on 2024-09-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0003_rename_timeditor_castmodel_ditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='ditor',
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='cashmethodid',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='cashmethodname',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='datemiladi',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='dateshamsi',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='filenumber',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='idf',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='melicodeoperatore',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='melicodvarizande',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
