# Generated by Django 4.1.7 on 2024-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0003_castmodel_datemiladi_castmodel_dateshamsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='cashmethodid',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='cashmethodname',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='mablagh',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='melicodeoperatore',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
