# Generated by Django 4.1.7 on 2024-05-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0004_alter_castmodel_bankonvan_alter_castmodel_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='off',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='peyment',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
