# Generated by Django 4.1.7 on 2024-09-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0004_castmodel_cashmethodid_castmodel_cashmethodname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmodel',
            name='dateshamsieditor',
            field=models.CharField(default='0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='mablagh',
            field=models.CharField(blank=True, default='0', max_length=500, null=True),
        ),
    ]
