# Generated by Django 4.1.7 on 2024-12-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0005_alter_castmodel_dateshamsieditor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='bankpeyment',
            field=models.CharField(default='-3', max_length=200, null=True),
        ),
    ]
