# Generated by Django 4.1.7 on 2024-05-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0005_castmodel_off_alter_castmodel_peyment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='bankonvan',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='melicodevarizande',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='mounth',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='off',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='operatore',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='year',
        ),
    ]
