# Generated by Django 4.1.7 on 2024-05-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0006_remove_castmodel_bankonvan_remove_castmodel_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='casttestmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peyment', models.CharField(default='0', max_length=20)),
                ('selectjob', models.CharField(default='0', max_length=100)),
                ('persone', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='castmodel',
            name='bankonvan',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='day',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='melicodevarizande',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='mounth',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='off',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='operatore',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='year',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
