# Generated by Django 4.1.7 on 2024-05-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0007_casttestmodel_castmodel_bankonvan_castmodel_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casttestmodel',
            old_name='persone',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='casttestmodel',
            old_name='peyment',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='casttestmodel',
            old_name='selectjob',
            new_name='s',
        ),
    ]
