# Generated by Django 4.1.7 on 2024-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0008_rename_persone_casttestmodel_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='pardakht',
            field=models.CharField(default='پرداخت نشده', max_length=100),
        ),
    ]
