# Generated by Django 4.1.7 on 2024-06-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0009_castmodel_pardakht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='pardakht',
        ),
    ]
