# Generated by Django 4.1.7 on 2024-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0012_alter_castmodel_beyane'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='ghabelpardakht',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
