# Generated by Django 4.1.7 on 2024-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0013_castmodel_ghabelpardakht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castmodel',
            old_name='bankonvan',
            new_name='cashmethod',
        ),
        migrations.RenameField(
            model_name='castmodel',
            old_name='day',
            new_name='datemiladi',
        ),
        migrations.RenameField(
            model_name='castmodel',
            old_name='mounth',
            new_name='dateshamsi',
        ),
        migrations.RenameField(
            model_name='castmodel',
            old_name='persone',
            new_name='filenumber',
        ),
        migrations.RenameField(
            model_name='castmodel',
            old_name='off',
            new_name='idf',
        ),
        migrations.RenameField(
            model_name='castmodel',
            old_name='selectjob',
            new_name='mablagh',
        ),
        migrations.RenameField(
            model_name='castmodel',
            old_name='year',
            new_name='melicodeoperatore',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='beyane',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='ghabelpardakht',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='melicodevarizande',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='operatore',
        ),
        migrations.RemoveField(
            model_name='castmodel',
            name='peyment',
        ),
        migrations.AddField(
            model_name='castmodel',
            name='melicodvarizande',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
