# Generated by Django 4.1.7 on 2024-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0014_rename_bankonvan_castmodel_cashmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='listmodeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
