# Generated by Django 4.1.7 on 2024-07-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0015_listmodeltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idf', models.CharField(default='0', max_length=20)),
                ('melicodvarizande', models.CharField(default='0', max_length=100)),
                ('dateshamsi', models.CharField(default='0', max_length=100)),
                ('datemiladi', models.CharField(default='0', max_length=100)),
                ('filenumber', models.CharField(default='0', max_length=100)),
                ('cashmethod', models.CharField(default='0', max_length=100)),
                ('melicodeoperatore', models.CharField(default='0', max_length=100)),
                ('mablagh', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
