# Generated by Django 4.1.7 on 2024-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0016_ctmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctmodel',
            name='cashmethod',
        ),
        migrations.RemoveField(
            model_name='ctmodel',
            name='datemiladi',
        ),
        migrations.RemoveField(
            model_name='ctmodel',
            name='dateshamsi',
        ),
        migrations.RemoveField(
            model_name='ctmodel',
            name='filenumber',
        ),
        migrations.RemoveField(
            model_name='ctmodel',
            name='mablagh',
        ),
        migrations.RemoveField(
            model_name='ctmodel',
            name='melicodeoperatore',
        ),
        migrations.RemoveField(
            model_name='ctmodel',
            name='melicodvarizande',
        ),
    ]
