# Generated by Django 4.1.7 on 2024-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0019_remove_castmodel_cashmethod_castmodel_cashmethodid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='dateshamsieditor',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='castmodel',
            name='melicodvarizande',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
