# Generated by Django 4.1.7 on 2024-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0020_castmodel_dateshamsieditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmodel',
            name='dateshamsieditor',
            field=models.CharField(default='noedit', max_length=10),
        ),
    ]
