# Generated by Django 4.1.7 on 2024-09-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0021_alter_castmodel_dateshamsieditor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castmodel',
            old_name='dateshamsieditor',
            new_name='timeditor',
        ),
    ]
