# Generated by Django 4.1.7 on 2023-06-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='nameofmaterial',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='numberofmaterial',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
