# Generated by Django 4.1.7 on 2024-05-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmodel',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='workmodel',
            name='detalework',
        ),
        migrations.RemoveField(
            model_name='workmodel',
            name='person',
        ),
        migrations.RemoveField(
            model_name='workmodel',
            name='time',
        ),
    ]
