# Generated by Django 4.1.7 on 2024-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_remove_workmodel_cast_remove_workmodel_detalework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobselectormodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(default='تزریقات', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='workmodel',
            name='cast',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='detalework',
            field=models.CharField(default='تزریقات', max_length=150),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='person',
            field=models.CharField(default='من', max_length=150),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='time',
            field=models.CharField(default='امروز', max_length=50),
        ),
    ]
