# Generated by Django 4.1.7 on 2024-05-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_jobselectormodel_workmodel_cast_workmodel_detalework_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobselectormodel',
            old_name='work',
            new_name='w',
        ),
    ]
