# Generated by Django 4.1.7 on 2024-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0004_rename_work_jobselectormodel_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='idjob',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
