# Generated by Django 4.1.7 on 2024-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0007_alter_workmodel_vahed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='melicodpersonel',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
