# Generated by Django 4.1.7 on 2024-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_workmodel_melicodpersonel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='berand',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
