# Generated by Django 4.1.7 on 2024-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0009_workmodel_berand'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='esmekala',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
