# Generated by Django 4.1.7 on 2024-08-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0010_workmodel_esmekala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='berand',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='esmekala',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
