# Generated by Django 4.1.7 on 2024-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0011_alter_workmodel_berand_alter_workmodel_esmekala'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='idbrand',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
