# Generated by Django 4.1.7 on 2024-09-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0012_workmodel_idbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='idbrand',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
