# Generated by Django 4.1.7 on 2024-09-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0014_alter_workmodel_idbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='idbrand',
            field=models.IntegerField(default=0),
        ),
    ]
