# Generated by Django 4.1.7 on 2025-01-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0015_alter_workmodel_idbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='hidde',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
