# Generated by Django 4.1.7 on 2024-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gharardad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melicode', models.CharField(max_length=10)),
                ('type_select', models.CharField(max_length=20)),
                ('job_select', models.CharField(default='0', max_length=50)),
                ('cast', models.CharField(max_length=20)),
            ],
        ),
    ]
