# Generated by Django 4.1.7 on 2024-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gharardadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melicod', models.CharField(max_length=10)),
                ('type_select', models.CharField(max_length=20)),
                ('job_select', models.CharField(default='0', max_length=50)),
                ('cast', models.CharField(max_length=20)),
                ('modirmelicod', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=5)),
                ('muonth', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='gharardad',
        ),
    ]
