# Generated by Django 4.1.7 on 2024-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0002_gharardadmodel_delete_gharardad'),
    ]

    operations = [
        migrations.CreateModel(
            name='pardakhtshodemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peyment', models.CharField(default='0', max_length=20)),
                ('off', models.CharField(default='0', max_length=20)),
                ('melicodevarizande', models.CharField(default='0', max_length=11)),
                ('selectjob', models.CharField(default='0', max_length=100)),
                ('bankonvan', models.CharField(default='0', max_length=100)),
                ('persone', models.CharField(default='0', max_length=100)),
                ('operatore', models.CharField(default='0', max_length=11)),
                ('day', models.CharField(default='0', max_length=100)),
                ('mounth', models.CharField(default='0', max_length=100)),
                ('year', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
