# Generated by Django 4.1.7 on 2024-06-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0003_pardakhtshodemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='savemovaghat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoghoghmelicod', models.CharField(default='0', max_length=11)),
                ('idcod', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
