# Generated by Django 4.1.7 on 2024-07-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0004_savemovaghat'),
    ]

    operations = [
        migrations.CreateModel(
            name='esmekalamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esmekala', models.CharField(default='0', max_length=11)),
            ],
        ),
    ]
