# Generated by Django 4.1.7 on 2024-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0005_esmekalamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmekalamodel',
            name='berand',
            field=models.CharField(default='0', max_length=10000),
        ),
        migrations.AlterField(
            model_name='esmekalamodel',
            name='esmekala',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
