# Generated by Django 4.1.7 on 2024-08-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0006_esmekalamodel_berand_alter_esmekalamodel_esmekala'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmekalamodel',
            name='jobid',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='esmekalamodel',
            name='berand',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='esmekalamodel',
            name='esmekala',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
