# Generated by Django 4.1.7 on 2024-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0007_esmekalamodel_jobid_alter_esmekalamodel_berand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmekalamodel',
            name='unit',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='esmekalamodel',
            name='value',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
