# Generated by Django 4.1.7 on 2024-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0008_esmekalamodel_unit_esmekalamodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esmekalamodel',
            name='value',
            field=models.CharField(default='ندارد', max_length=1000),
        ),
    ]
