# Generated by Django 4.1.7 on 2024-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0012_froshandemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='waremodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kala', models.CharField(max_length=200)),
                ('froshande', models.CharField(max_length=150)),
                ('castmethode', models.CharField(default='پرداخت نشده', max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
