# Generated by Django 4.1.7 on 2024-12-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0013_waremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='anbarmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalaid', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
    ]
