# Generated by Django 4.1.7 on 2024-12-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0014_anbarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbarmodel',
            name='dateday',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anbarmodel',
            name='datemounth',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anbarmodel',
            name='dateyear',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
