# Generated by Django 4.1.7 on 2024-12-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0016_anbargardanimodel_remove_anbarmodel_dateday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waremodel',
            name='day',
            field=models.CharField(default='0', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='waremodel',
            name='factornumber',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='waremodel',
            name='mounth',
            field=models.CharField(default='0', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='waremodel',
            name='year',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
    ]
