# Generated by Django 4.1.7 on 2025-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0017_waremodel_day_waremodel_factornumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbargardanimodel',
            name='chengermelicode',
            field=models.CharField(default='0', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='anbargardanimodel',
            name='newvalue',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anbargardanimodel',
            name='dateday',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anbargardanimodel',
            name='datemounth',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anbargardanimodel',
            name='dateyear',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anbargardanimodel',
            name='kalaid',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anbargardanimodel',
            name='value',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
