# Generated by Django 4.1.7 on 2025-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0018_anbargardanimodel_chengermelicode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waremodel',
            name='tahvil',
            field=models.CharField(default='0', max_length=2, null=True),
        ),
    ]
