# Generated by Django 4.1.7 on 2025-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0019_waremodel_tahvil'),
    ]

    operations = [
        migrations.AddField(
            model_name='waremodel',
            name='savermelicode',
            field=models.CharField(default='0', max_length=12, null=True),
        ),
    ]
