# Generated by Django 4.1.7 on 2025-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0020_waremodel_savermelicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='waremodel',
            name='takhfif',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
