# Generated by Django 4.1.7 on 2025-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0021_waremodel_takhfif'),
    ]

    operations = [
        migrations.AddField(
            model_name='waremodel',
            name='pardakht',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
