# Generated by Django 4.1.7 on 2025-01-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy_app', '0022_waremodel_pardakht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waremodel',
            name='cast',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='waremodel',
            name='takhfif',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
