# Generated by Django 4.1.7 on 2024-12-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accuntmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dataacont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('melicode', models.CharField(default='0', max_length=20)),
                ('phonnumber', models.CharField(default='0', max_length=20)),
                ('berthday', models.CharField(max_length=100)),
                ('miladiarray', models.CharField(default='0', max_length=5000)),
                ('shamsiarray', models.CharField(default='0', max_length=5000)),
                ('showclandarray', models.CharField(default='0', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='phonnambermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100)),
                ('lastname', models.CharField(default='0', max_length=100)),
                ('phonnumber', models.CharField(default='0', max_length=20)),
                ('saver', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='savecodphon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('melicode', models.CharField(default='0', max_length=20)),
                ('phonnumber', models.CharField(default='0', max_length=20)),
                ('berthdayyear', models.CharField(max_length=100)),
                ('berthdayday', models.CharField(max_length=100)),
                ('berthdaymounth', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('expaiercode', models.CharField(max_length=20)),
            ],
        ),
    ]
