# Generated by Django 4.1.7 on 2024-12-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='dayb',
            field=models.CharField(default='0', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='level',
            field=models.CharField(default='دسترسی معمولی', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='melicode',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='mountb',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='pasword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='phonnumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='savesabt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accuntmodel',
            name='yearb',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='accuntmodel',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accuntmodel',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
