# Generated by Django 4.1.7 on 2024-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='melicode',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
    ]
