# Generated by Django 4.1.7 on 2024-12-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0002_accuntmodel_melicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='phonnumber',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
