# Generated by Django 4.1.7 on 2024-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0002_dataacont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savecodphon',
            old_name='berthday',
            new_name='berthdayday',
        ),
        migrations.AddField(
            model_name='savecodphon',
            name='berthdaymounth',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savecodphon',
            name='berthdayyear',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
