# Generated by Django 4.1.7 on 2024-12-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0002_accuntmodel_melicode_alter_accuntmodel_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuntmodel',
            name='melicode',
        ),
    ]
