# Generated by Django 4.1.7 on 2024-12-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0003_accuntmodel_phonnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuntmodel',
            name='melicode',
        ),
    ]
