# Generated by Django 4.1.7 on 2024-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0004_remove_dataacont_berthday_remove_dataacont_melicode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonnamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phonnumber', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dataacont',
            name='berthday',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataacont',
            name='melicode',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='dataacont',
            name='miladiarray',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.AddField(
            model_name='dataacont',
            name='shamsiarray',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.AddField(
            model_name='dataacont',
            name='showclandarray',
            field=models.CharField(default='0', max_length=5000),
        ),
    ]
