# Generated by Django 4.1.7 on 2024-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0005_phonnamber_dataacont_berthday_dataacont_melicode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonnambermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phonnumber', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='phonnamber',
        ),
    ]
