# Generated by Django 4.1.7 on 2024-05-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0006_phonnambermodel_delete_phonnamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonnambermodel',
            name='lastname',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonnambermodel',
            name='name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
