# Generated by Django 4.1.7 on 2024-05-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0008_accuntmodel_dayb_accuntmodel_mountb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonnambermodel',
            name='saver',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
