# Generated by Django 4.1.7 on 2024-08-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0009_phonnambermodel_saver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuntmodel',
            name='melicode',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='accuntmodel',
            name='phonnumber',
            field=models.CharField(max_length=11),
        ),
    ]
