# Generated by Django 4.1.7 on 2024-11-12 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0010_alter_accuntmodel_melicode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='datesave',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
