# Generated by Django 4.1.7 on 2024-11-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0011_accuntmodel_datesave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuntmodel',
            name='datesave',
        ),
    ]
