# Generated by Django 4.1.7 on 2024-12-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0012_remove_accuntmodel_datesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='savesabt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accuntmodel',
            name='berthday',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
