# Generated by Django 4.1.7 on 2024-12-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0012_remove_accuntmodel_datesave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accuntmodel',
            old_name='berthday',
            new_name='savesabt',
        ),
    ]
