# Generated by Django 4.1.7 on 2024-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0013_rename_berthday_accuntmodel_savesabt'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='berthday',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
