# Generated by Django 4.1.7 on 2024-12-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0013_accuntmodel_savesabt_alter_accuntmodel_berthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuntmodel',
            name='berthday',
        ),
    ]
