# Generated by Django 4.1.7 on 2024-12-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0015_remove_accuntmodel_savesabt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuntmodel',
            name='dayb',
        ),
        migrations.RemoveField(
            model_name='accuntmodel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='accuntmodel',
            name='melicode',
        ),
        migrations.RemoveField(
            model_name='accuntmodel',
            name='mountb',
        ),
        migrations.RemoveField(
            model_name='accuntmodel',
            name='pasword',
        ),
        migrations.RemoveField(
            model_name='accuntmodel',
            name='phonnumber',
        ),
        migrations.RemoveField(
            model_name='accuntmodel',
            name='yearb',
        ),
    ]
