# Generated by Django 4.1.7 on 2024-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filepage1model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mellicode', models.CharField(default='0', max_length=12)),
                ('inject_botax', models.CharField(default='0', max_length=150)),
                ('illnes', models.CharField(default='0', max_length=150)),
                ('drug', models.CharField(default='0', max_length=150)),
                ('sensivety', models.CharField(default='0', max_length=150)),
                ('pregnancy', models.CharField(default='0', max_length=150)),
                ('date_finaly', models.CharField(default='0', max_length=150)),
                ('image_show', models.CharField(default='0', max_length=150)),
                ('satisfact', models.CharField(default='0', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='fpeseshktestmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melicod', models.CharField(default='0', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='leavemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelmelicod', models.CharField(default='0', max_length=11)),
                ('dateshamsi', models.CharField(default='0', max_length=50)),
                ('datemiladi', models.CharField(default='0', max_length=50)),
                ('muont', models.CharField(default='0', max_length=50)),
                ('leave', models.TextField(default='0', max_length=10000000000)),
            ],
        ),
        migrations.CreateModel(
            name='neursemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mellicode', models.CharField(default='0', max_length=12)),
                ('inject_botax', models.CharField(default='0', max_length=150)),
                ('illnes', models.CharField(default='0', max_length=150)),
                ('drug', models.CharField(default='0', max_length=150)),
                ('sensivety', models.CharField(default='0', max_length=150)),
                ('pregnancy', models.CharField(default='0', max_length=150)),
                ('date_finaly', models.CharField(default='0', max_length=150)),
                ('image_show', models.CharField(default='0', max_length=150)),
                ('satisfact', models.CharField(default='0', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='reservemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melicod', models.CharField(default='0', max_length=150)),
                ('jobreserv', models.CharField(default='0', max_length=150)),
                ('detalereserv', models.CharField(default='0', max_length=150)),
                ('personreserv', models.CharField(default='0', max_length=150)),
                ('timereserv', models.CharField(default='0', max_length=150)),
                ('castreserv', models.CharField(default='0', max_length=150)),
                ('numbertime', models.CharField(default='0', max_length=10)),
                ('hourreserv', models.CharField(default='0', max_length=10)),
                ('dateshamsireserv', models.CharField(default='0', max_length=150)),
                ('datemiladireserv', models.CharField(default='0', max_length=150)),
                ('yearshamsi', models.CharField(default='0', max_length=10)),
                ('cardnumber', models.CharField(default='0', max_length=20)),
                ('pyment', models.CharField(default='0', max_length=20)),
                ('trakingcod', models.CharField(default='0', max_length=20)),
                ('bank', models.CharField(default='0', max_length=20)),
                ('checking', models.CharField(default='false', max_length=20)),
                ('vahed', models.CharField(default='0', max_length=100, null=True)),
                ('idwork', models.CharField(default='0', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservemodeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mellicode', models.CharField(default='0', max_length=12)),
                ('jobreserv', models.CharField(default='0', max_length=150)),
                ('detalereserv', models.CharField(default='0', max_length=150)),
                ('personreserv', models.CharField(default='0', max_length=150)),
                ('timereserv', models.CharField(default='0', max_length=150)),
                ('castreserv', models.CharField(default='0', max_length=150)),
                ('numbertime', models.CharField(default='0', max_length=10)),
                ('hourreserv', models.CharField(default='0', max_length=10)),
                ('dateshamsireserv', models.CharField(default='0', max_length=150)),
                ('datemiladireserv', models.CharField(default='0', max_length=150)),
                ('yearshamsi', models.CharField(default='0', max_length=10)),
                ('message', models.CharField(default='0', max_length=20)),
                ('cardnumber', models.CharField(default='0', max_length=20)),
                ('rahgiricod', models.CharField(default='0', max_length=20)),
                ('phonnumber', models.CharField(default='0', max_length=12)),
                ('fiestname', models.CharField(default='0', max_length=150)),
                ('lastname', models.CharField(default='0', max_length=150)),
                ('vahed', models.CharField(default='', max_length=100)),
                ('idwork', models.CharField(default='0', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchmodeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
