# Generated by Django 4.1.7 on 2024-09-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='datemiladi',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='dateshamsi',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='muont',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='date_finaly',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='image_show',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='satisfact',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='sensivety',
        ),
    ]
