# Generated by Django 4.1.7 on 2024-09-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filepage1model',
        ),
        migrations.DeleteModel(
            name='fpeseshktestmodel',
        ),
        migrations.DeleteModel(
            name='leavemodel',
        ),
        migrations.DeleteModel(
            name='neursemodel',
        ),
        migrations.DeleteModel(
            name='reservemodel',
        ),
        migrations.DeleteModel(
            name='reservemodeltest',
        ),
        migrations.DeleteModel(
            name='searchmodeltest',
        ),
    ]
