# Generated by Django 4.1.7 on 2024-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodeltest',
            name='cardnumber',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='fiestname',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='lastname',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='message',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='phonnumber',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='rahgiricod',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
