# Generated by Django 4.1.7 on 2024-09-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepage1model',
            name='date_finaly',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='illnes',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='image_show',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='inject_botax',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='satisfact',
        ),
        migrations.RemoveField(
            model_name='filepage1model',
            name='sensivety',
        ),
    ]
