# Generated by Django 4.1.7 on 2024-09-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='apbadimage',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='apghablimage',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='castreserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='checking',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='coment',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='datemiladireserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='dateshamsireserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='hourreserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='llateralbadimage',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='llateralghablimage',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='materiyal',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='numbertime',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='personreserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='pyment',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='reservid',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='rlateralbadimage',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='timereserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='trakingcod',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='vahedeobject',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='vahedeobjectname',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='valueunit',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='yearshamsi',
        ),
    ]
