# Generated by Django 4.1.7 on 2024-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0002_remove_leavemodel_datemiladi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='detalereserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='jobreserv',
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='datemiladi',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='dateshamsi',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='leave',
            field=models.TextField(default='0', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='muont',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='neursemodel',
            name='date_finaly',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='neursemodel',
            name='drug',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='neursemodel',
            name='image_show',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='neursemodel',
            name='pregnancy',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='neursemodel',
            name='satisfact',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='neursemodel',
            name='sensivety',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
