# Generated by Django 4.1.7 on 2024-09-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0002_remove_fpeseshktestmodel_apbadimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='detalereserv',
        ),
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='jobreserv',
        ),
    ]
