# Generated by Django 4.1.7 on 2024-03-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0002_reservemodeltest_cardnumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='neursetestmodel',
            new_name='filepage1model',
        ),
    ]
