# Generated by Django 4.1.7 on 2024-06-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0003_rename_neursetestmodel_filepage1model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='checking',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
