# Generated by Django 4.1.7 on 2024-09-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservemodeltest',
            name='detalereserv',
        ),
        migrations.RemoveField(
            model_name='reservemodeltest',
            name='jobreserv',
        ),
    ]
