# Generated by Django 4.1.7 on 2024-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0004_remove_reservemodeltest_detalereserv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodeltest',
            name='detalereserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='jobreserv',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
