# Generated by Django 4.1.7 on 2024-06-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0005_alter_reservemodel_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='vahed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='vahed',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
