# Generated by Django 4.1.7 on 2024-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0006_fpeseshktestmodel_detalereserv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodeltest',
            name='vaziyatereserv',
            field=models.CharField(default='رزرو', max_length=12),
        ),
    ]
