# Generated by Django 4.1.7 on 2024-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0006_reservemodel_vahed_reservemodeltest_vahed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='vahed',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
