# Generated by Django 4.1.7 on 2024-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0007_reservemodeltest_vaziyatereserv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservemodeltest',
            name='vaziyatereserv',
        ),
        migrations.AddField(
            model_name='reservemodel',
            name='vaziyatereserv',
            field=models.CharField(default='r', max_length=12),
        ),
    ]
