# Generated by Django 4.1.7 on 2024-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0007_alter_reservemodel_vahed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodeltest',
            name='vahed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
