# Generated by Django 4.1.7 on 2024-09-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0008_remove_reservemodeltest_vaziyatereserv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='vaziyatereserv',
            field=models.CharField(default='رزرو', max_length=12),
        ),
    ]
