# Generated by Django 4.1.7 on 2024-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0008_alter_reservemodeltest_vahed'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchmodeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
