# Generated by Django 4.1.7 on 2024-08-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0011_alter_leavemodel_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='idwork',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='idwork',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
