# Generated by Django 4.1.7 on 2025-05-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0012_monthlyleave_onetimeleave_weeklyleave_delete_leav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeleave',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='weeklyleave',
            name='operator',
        ),
        migrations.DeleteModel(
            name='MonthlyLeave',
        ),
        migrations.DeleteModel(
            name='OneTimeLeave',
        ),
        migrations.DeleteModel(
            name='WeeklyLeave',
        ),
    ]
