# Generated by Django 4.1.7 on 2025-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0013_remove_onetimeleave_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemodel',
            old_name='datemiladi',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='dateshamsi',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='muont',
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='leave',
            field=models.TextField(default='0', max_length=10000),
        ),
    ]
