# Generated by Django 4.1.7 on 2024-08-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0013_fpeseshktestmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpeseshktestmodel',
            old_name='material',
            new_name='materiyal',
        ),
    ]
