# Generated by Django 4.1.7 on 2024-09-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0014_rename_material_fpeseshktestmodel_materiyal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpeseshktestmodel',
            name='valueunit',
            field=models.CharField(default='0', max_length=9999),
        ),
    ]
