# Generated by Django 4.1.7 on 2025-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0014_rename_datemiladi_leavemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='vaziyatereserv',
            field=models.CharField(default='رزرو', max_length=100),
        ),
    ]
