# Generated by Django 4.1.7 on 2025-07-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0015_alter_reservemodel_vaziyatereserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='vaziyatereserv',
            field=models.CharField(default='هماهنگی روز قبل انجام نشده است', max_length=100),
        ),
    ]
