# Generated by Django 4.1.7 on 2024-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0015_fpeseshktestmodel_valueunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='castreserv',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='coment',
            field=models.TextField(default='0', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='datemiladireserv',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='dateshamsireserv',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='jobreserv',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='materiyal',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='melicod',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='timereserv',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='valueunit',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
