# Generated by Django 4.1.7 on 2026-02-13 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cantact_app', '0008_alter_accuntmodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب پیام',
                'verbose_name_plural': 'قالب\u200cهای پیام',
            },
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='متن ارسالی')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], default='success', max_length=10, verbose_name='وضعیت')),
                ('api_response', models.TextField(blank=True, null=True, verbose_name='پاسخ API')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='مخاطب')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.messagetemplate', verbose_name='قالب پیام')),
            ],
            options={
                'verbose_name': 'پیام ارسالی',
                'verbose_name_plural': 'پیام\u200cهای ارسالی',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('sender_number', models.CharField(max_length=11, verbose_name='شماره فرستنده')),
                ('received_at', models.DateTimeField(verbose_name='زمان دریافت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه پیام در کاوه\u200cنگار')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='مخاطب')),
            ],
            options={
                'verbose_name': 'پیام دریافتی',
                'verbose_name_plural': 'پیام\u200cهای دریافتی',
                'ordering': ['-received_at'],
            },
        ),
    ]
