# Generated by Django 4.1.7 on 2024-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melicod', models.CharField(default='0', max_length=150)),
                ('jobreserv', models.CharField(default='0', max_length=150)),
                ('detalereserv', models.CharField(default='0', max_length=150)),
                ('personreserv', models.CharField(default='0', max_length=150)),
                ('timereserv', models.CharField(default='0', max_length=150)),
                ('castreserv', models.CharField(default='0', max_length=150)),
                ('numbertime', models.CharField(default='0', max_length=10)),
                ('hourreserv', models.CharField(default='0', max_length=10)),
                ('dateshamsireserv', models.CharField(default='0', max_length=150)),
                ('datemiladireserv', models.CharField(default='0', max_length=150)),
                ('yearshamsi', models.CharField(default='0', max_length=10)),
                ('cardnumber', models.CharField(default='0', max_length=20)),
                ('pyment', models.CharField(default='0', max_length=20)),
                ('trakingcod', models.CharField(default='0', max_length=20)),
                ('bank', models.CharField(default='0', max_length=20)),
                ('checking', models.CharField(default='false', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='image/rlateralbad')),
                ('coment', models.TextField(default='')),
                ('vahedeobject', models.CharField(default='0', max_length=10)),
                ('offer', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
