# Generated by Django 4.1.7 on 2024-08-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpeseshktestmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melicod', models.CharField(default='0', max_length=150)),
                ('jobreserv', models.CharField(default='0', max_length=150)),
                ('detalereserv', models.CharField(default='0', max_length=150)),
                ('personreserv', models.CharField(default='0', max_length=150)),
                ('timereserv', models.CharField(default='0', max_length=150)),
                ('castreserv', models.CharField(default='0', max_length=150)),
                ('numbertime', models.CharField(default='0', max_length=10)),
                ('hourreserv', models.CharField(default='0', max_length=10)),
                ('dateshamsireserv', models.CharField(default='0', max_length=150)),
                ('datemiladireserv', models.CharField(default='0', max_length=150)),
                ('yearshamsi', models.CharField(default='0', max_length=10)),
                ('cardnumber', models.CharField(default='0', max_length=20)),
                ('pyment', models.CharField(default='0', max_length=20)),
                ('trakingcod', models.CharField(default='0', max_length=20)),
                ('bank', models.CharField(default='0', max_length=20)),
                ('checking', models.CharField(default='false', max_length=20)),
                ('apghablimage', models.ImageField(null=True, upload_to='image/apghabl')),
                ('llateralghablimage', models.ImageField(null=True, upload_to='image/llateralghabl')),
                ('apbadimage', models.ImageField(null=True, upload_to='image/apbad')),
                ('llateralbadimage', models.ImageField(null=True, upload_to='image/llateralbad')),
                ('rlateralbadimage', models.ImageField(null=True, upload_to='image/rlateralbad')),
                ('coment', models.TextField(default='0', max_length=10000000000)),
                ('vahedeobject', models.CharField(default='1', max_length=10)),
                ('vahedeobjectname', models.CharField(default='0', max_length=100, null=True)),
                ('offer', models.CharField(default='0', max_length=20)),
                ('reservid', models.CharField(default='0', max_length=50)),
                ('material', models.CharField(default='0', max_length=9999)),
            ],
        ),
        migrations.DeleteModel(
            name='filemodel',
        ),
    ]
