# Generated by Django 4.1.7 on 2024-06-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_fpeseshktestmodel_delete_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='vahedeobjectname',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
