# Generated by Django 4.1.7 on 2024-08-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_fpeseshktestmodel_delete_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fpeseshktestmodel',
        ),
    ]
