# Generated by Django 4.1.7 on 2024-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_alter_fpeseshktestmodel_vahedeobjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='reservid',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='vahedeobject',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='vahedeobjectname',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
