# Generated by Django 4.1.7 on 2024-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_alter_fpeseshktestmodel_reservid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='fpeseshktestmodel',
            name='apbadimage',
            field=models.ImageField(null=True, upload_to='image/apbad'),
        ),
        migrations.AddField(
            model_name='fpeseshktestmodel',
            name='apghablimage',
            field=models.ImageField(null=True, upload_to='image/apghabl'),
        ),
        migrations.AddField(
            model_name='fpeseshktestmodel',
            name='llateralbadimage',
            field=models.ImageField(null=True, upload_to='image/llateralbad'),
        ),
        migrations.AddField(
            model_name='fpeseshktestmodel',
            name='llateralghablimage',
            field=models.ImageField(null=True, upload_to='image/llateralghabl'),
        ),
        migrations.AddField(
            model_name='fpeseshktestmodel',
            name='rlateralbadimage',
            field=models.ImageField(null=True, upload_to='image/rlateralbad'),
        ),
    ]
