# Generated by Django 4.1.7 on 2024-08-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_fpeseshktesttmodel_fpeseshktestmodel_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpeseshkmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idreserv', models.CharField(default='0', max_length=999999)),
                ('material', models.CharField(default='0', max_length=9999999)),
            ],
        ),
        migrations.DeleteModel(
            name='fpeseshktesttmodel',
        ),
    ]
