# Generated by Django 4.1.7 on 2024-08-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_fpeseshkmodel_delete_fpeseshktesttmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fpeseshkmodel',
        ),
    ]
