# Generated by Django 4.1.7 on 2024-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0008_delete_fpeseshkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpeseshktestmodel',
            name='material',
            field=models.CharField(default='0', max_length=9999),
        ),
    ]
