# Generated by Django 4.1.7 on 2024-08-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0009_alter_fpeseshktestmodel_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpeseshktestmodel',
            old_name='material',
            new_name='materialll',
        ),
    ]
