# Generated by Django 4.1.7 on 2024-08-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0010_rename_material_fpeseshktestmodel_materialll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpeseshktestmodel',
            name='materialll',
        ),
    ]
