# Generated by Django 4.1.7 on 2024-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mesaagecuntermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('cunt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mesaagetextmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mesaagetext', models.TextField(max_length=900000)),
            ],
        ),
    ]
