# Generated by Django 4.1.7 on 2024-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaagecuntermodel',
            name='date',
        ),
        migrations.AddField(
            model_name='mesaagecuntermodel',
            name='dateday',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='mesaagecuntermodel',
            name='datemuonth',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='mesaagecuntermodel',
            name='dateweek',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='mesaagecuntermodel',
            name='dateyear',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='mesaagecuntermodel',
            name='cunt',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='mesaagecuntermodel',
            name='name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='mesaagecuntermodel',
            name='sender',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='mesaagetextmodel',
            name='mesaagetext',
            field=models.TextField(default='0', max_length=900000),
        ),
        migrations.AlterField(
            model_name='mesaagetextmodel',
            name='name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
