# Generated by Django 4.1.7 on 2024-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0002_remove_mesaagecuntermodel_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeimgmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100)),
                ('image', models.ImageField(upload_to='image/home')),
            ],
        ),
    ]
