# Generated by Django 4.1.7 on 2024-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0004_homemenosarimodel_alter_homeimgmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homemobilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/home')),
            ],
        ),
    ]
