# Generated by Django 4.1.7 on 2024-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0005_homemobilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimgmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/homepc'),
        ),
        migrations.AlterField(
            model_name='homemenosarimodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/menosari'),
        ),
        migrations.AlterField(
            model_name='homemobilemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/homemobile'),
        ),
    ]
