# Generated by Django 4.1.7 on 2024-06-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0006_alter_homeimgmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimgmodel',
            name='size',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
