# Generated by Django 4.1.7 on 2024-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0007_homeimgmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemobilemodel',
            name='size',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
