# Generated by Django 4.1.7 on 2024-06-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0008_homemobilemodel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimgmodel',
            name='size',
        ),
        migrations.RemoveField(
            model_name='homemobilemodel',
            name='size',
        ),
    ]
