# Generated by Django 4.1.7 on 2024-09-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('it_app', '0010_delete_homeimgmodel_delete_homemenosarimodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeimgmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/homepc')),
            ],
        ),
        migrations.CreateModel(
            name='homemenosarimodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/menosari')),
            ],
        ),
        migrations.CreateModel(
            name='homemobilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/homemobile')),
            ],
        ),
        migrations.CreateModel(
            name='mesaagecuntermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100)),
                ('dateyear', models.CharField(default='0', max_length=100)),
                ('datemuonth', models.CharField(default='0', max_length=100)),
                ('dateday', models.CharField(default='0', max_length=100)),
                ('dateweek', models.CharField(default='0', max_length=100)),
                ('sender', models.CharField(default='0', max_length=100)),
                ('cunt', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mesaagetextmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100)),
                ('mesaagetext', models.TextField(default='0', max_length=900000)),
            ],
        ),
    ]
