# Generated by Django 4.1.7 on 2024-09-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0012_mesaagemodel_delete_mesaagecuntermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaagemodel',
            name='vaziyat',
            field=models.CharField(default='در انتظار پاسخ', max_length=30),
        ),
    ]
