# Generated by Django 4.1.7 on 2024-09-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0013_mesaagemodel_vaziyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaagemodel',
            name='idtiket',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
