# Generated by Django 4.1.7 on 2024-09-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0014_mesaagemodel_idtiket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaagemodel',
            name='textmessage',
            field=models.TextField(default='0', max_length=10000000),
        ),
    ]
