# Generated by Django 4.1.7 on 2024-09-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0015_alter_mesaagemodel_textmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaagemodel',
            name='textmessage',
            field=models.TextField(default='0', max_length=1000000),
        ),
    ]
