# Generated by Django 4.1.7 on 2024-09-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0017_remove_mesaagemodel_phonnumber_mesaagemodel_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaagemodel',
            old_name='idtiket',
            new_name='dateweek',
        ),
    ]
