# Generated by Django 4.1.7 on 2024-09-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0018_rename_idtiket_mesaagemodel_dateweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaagemodel',
            name='hour',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='mesaagemodel',
            name='minute',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
