# Generated by Django 4.1.7 on 2024-09-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0019_alter_mesaagemodel_hour_alter_mesaagemodel_minute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaagemodel',
            old_name='melicod',
            new_name='recivermelicod',
        ),
    ]
